[rdf_data.endpoints.mardi]
query_url = "https://query.portal.mardi4nfdi.de/sparql"

[rdf_data.endpoints.mardi.prefixmap]
wd = "https://portal.mardi4nfdi.de/entity/"
wdt = "https://portal.mardi4nfdi.de/prop/direct/"
schema = "http://schema.org/"
p = "https://portal.mardi4nfdi.de/prop/"
wbo = "http://wikiba.se/ontology#"
rdfs = "http://www.w3.org/2000/01/rdf-schema#"
skos = "http://www.w3.org/2004/02/skos/core#"
wds = "https://portal.mardi4nfdi.de/entity/statement/"
xsd = "http://www.w3.org/2001/XMLSchema#"
